# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64326f0a64738a90bce12b7f0cb951b155579e134e7e4cf5ad7c7ac29d5761a0bec856d67de802d81cbd9785c46c9f4256d92dbf2cfa6e2a964f9fc864176a49

test:
  secret_key_base: 48a3e004ccb3c7135d42010b1a68614cb1da24265dab78875ffec4dbd756ef8c7f1567babe184fb787afa3ee6b1d2ba8a4426603f479d992e2cd23277ac52f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
